Improve error handling of scripts

diff --git a/docker2qcow2 b/docker2qcow2
--- a/docker2qcow2
+++ b/docker2qcow2
@@ -1,45 +1,52 @@
 #!/bin/sh
 # Convert docker image to qcow2
 
+set -e
+trap 'exit' INT QUIT TERM
+
+die() {
+	echo "$@" >&2
+	exit 1
+}
+
 image=$1
 size=${2:-200}
 init=$(dirname -- "$0")/init/mininit
 
-if [ -z "$image" ]; then
-	echo "Usage: docker2qcow2 image [size]" >&2
-	exit 1
-fi
+[ -z "$image" ] && die "Usage: docker2qcow2 image [size_MB]"
+[ -f "$init" ] || die "Init program not found: $init"
 
-if [ ! -f "$init" ]; then
-	echo "Init program not found: $init" >&2
-	exit 1
-fi
+# check image size
+image_size=$(docker inspect --format '{{.Size}}' "$image")
+image_size=$(((image_size*13/10/1024 + 512)/1024))
+[ "$image_size" -gt "$size" ] && die "size should be at least ${image_size}MB"
 
 tempdir=$(mktemp -d)
 tempdocker=$(basename "$tempdir" | tr "A-Z." "a-z-" | tr -c -d "a-z0-9-")
-trap 'rm -rf "$tempdir"' EXIT
+trap 'rm -rf "$tempdir" 2> /dev/null' EXIT
 
 echo "Exporting docker image..."
 
 # convert docker image to temporary image with squashed layers
-printf 'FROM %s\nFROM scratch\nCOPY --from=0 / /\n' "$image" | docker build -t "$tempdocker" - > /dev/null || exit
+printf 'FROM %s\nFROM scratch\nCOPY --from=0 / /\n' "$image" | docker build -t "$tempdocker" - > /dev/null
 # save temporary image into tar file
 docker save -o "$tempdir/docker.tar" "$tempdocker"
 docker rmi "$tempdocker" > /dev/null
 tarfile=$(tar tf "$tempdir/docker.tar" | grep '\.tar$')
 # create raw image
-dd if=/dev/zero bs=1M count="$size" of="$tempdir/image.raw" status=none || exit
+dd if=/dev/zero bs=1M count="$size" of="$tempdir/image.raw" status=none
 mkdir "$tempdir/image"
 
 # extract tar file into raw ext4 image, add init program
-sudo sh -c "
+sudo sh -c -e "
+trap 'exit' INT QUIT TERM
 mke2fs -q -t ext4 '$tempdir/image.raw'
 mount '$tempdir/image.raw' '$tempdir/image'
+trap \"umount '$tempdir/image'\" EXIT
 tar xOf '$tempdir/docker.tar' '$tarfile' | tar x -C '$tempdir/image'
 rm -f '$tempdir/image/sbin/init'
 cp -- '$init' '$tempdir/image/sbin/init'
-umount '$tempdir/image'
-" || exit
+"
 
 # convert raw image to compressed qcow2
 qemu-img convert -c -f raw -O qcow2 "$tempdir/image.raw" "$image.qcow2"
diff --git a/kernel/mkinitramfs b/kernel/mkinitramfs
--- a/kernel/mkinitramfs
+++ b/kernel/mkinitramfs
@@ -1,31 +1,24 @@
 #!/bin/sh
 # Create initramfs
 
+set -e
+trap 'exit' INT QUIT TERM
+
+die() {
+	echo "$@" >&2
+	exit 1
+}
+
 template=$1
 version=$2
 
-if [ -z "$version" ]; then
-	echo "Usage: mkinitramfs ramfs-template version" >&2
-	exit 1
-fi
-
-if [ ! -d "$template" ]; then
-	echo "Template directory not found: $template" >&2
-	exit 1
-fi
-
-if [ ! -d "lib/modules/$version" ]; then
-	echo "Module directory not found: lib/modules/$version" >&2
-	exit 1
-fi
-
-if [ ! -f modules.ramfs ]; then
-	echo "List of ramfs modules not found: module.ramfs" >&2
-	exit 1
-fi
+[ -z "$version" ] && die "Usage: mkinitramfs ramfs-template version"
+[ -d "$template" ] || die "Template directory not found: $template"
+[ -d "lib/modules/$version" ] || die "Module directory not found: lib/modules/$version"
+[ -f modules.ramfs ] || die "List of ramfs modules not found: module.ramfs"
 
 tempdir=$(mktemp -d)
-trap 'rm -rf "$tempdir"' EXIT
+trap 'rm -rf "$tempdir" 2> /dev/null' EXIT
 
 echo "Creating initramfs..."
 
@@ -37,7 +30,7 @@ cp -p "lib/modules/$version"/modules.* "$tempdir/lib/modules/$version/"
 [ -f modules.autoload ] && cp -p modules.autoload "$tempdir"
 
 # set files user id to root
-sudo chown -R 0:0 "$tempdir"/* || exit
+sudo chown -R 0:0 "$tempdir"/*
 
 # create initramfs
 { cd "$tempdir"; find * -print0 | sort -z | cpio -o -0 --format=newc --quiet; } | gzip -9 > "initramfs-$version"
