Scripts - no longer use sudo

diff --git a/kernel/modules2qcow2 b/kernel/modules2qcow2
--- a/kernel/modules2qcow2
+++ b/kernel/modules2qcow2
@@ -1,18 +1,19 @@
 #!/bin/sh
 # Store modules into qcow2
 
+set -e
+trap 'exit' INT QUIT TERM
+
+die() {
+	echo "$@" >&2
+	exit 1
+}
+
 version=$1
 size=${2:-200}
 
-if [ -z "$version" ]; then
-	echo "Usage: modules2qcow2 version [size]" >&2
-	exit 1
-fi
-
-if [ ! -d "lib/modules/$version" ]; then
-	echo "Directory not found: lib/modules/$version" >&2
-	exit 1
-fi
+[ -n "$version" ] || die "Usage: modules2qcow2 version [size]"
+[ -d "lib/modules/$version" ] || die "Directory not found: lib/modules/$version"
 
 tempdir=$(mktemp -d)
 trap 'rm -rf "$tempdir"' EXIT
@@ -20,21 +21,22 @@ trap 'rm -rf "$tempdir"' EXIT
 echo "Copying modules..."
 
 # create missing modules.dep
-[ -f "lib/modules/$version/modules.dep" ] || /sbin/depmod -a -b . "$version"
+[ -f "lib/modules/$version/modules.dep" ] || \
+	PATH="/sbin:/usr/sbin:$PATH" depmod -a -b . "$version"
 
 # create raw image
-dd if=/dev/zero bs=1M count="$size" of="$tempdir/modules.raw" status=none || exit
-mkdir "$tempdir/modules"
+dd if=/dev/zero bs=1M count="$size" of="$tempdir/modules.raw" status=none
+PATH="/sbin:/usr/sbin:$PATH" mke2fs -q -t ext4 "$tempdir/modules.raw"
 
 # copy modules into raw image
-sudo sh -c "
-mke2fs -q -t ext4 '$tempdir/modules.raw'
-mount '$tempdir/modules.raw' '$tempdir/modules'
-cp -a 'lib/modules/$version' '$tempdir/modules'
-rm -f '$tempdir/modules/$version/build' '$tempdir/modules/$version/source'
-chown -R 0:0 '$tempdir/modules'/*
-umount '$tempdir/modules'
-" || exit
+mkdir "$tempdir/modules"
+docker run --rm --privileged --volume "$tempdir:/tempdir" --volume "$PWD/lib:/tempdir/lib" alpine sh -c -e "
+mount -o loop /tempdir/modules.raw /tempdir/modules
+cp -a '/tempdir/lib/modules/$version' /tempdir/modules
+rm -f '/tempdir/modules/$version/build' '/tempdir/modules/$version/source'
+chown -R 0:0 /tempdir/modules/*
+umount /tempdir/modules
+"
 
 # convert raw image to compressed qcow2
 qemu-img convert -c -f raw -O qcow2 "$tempdir/modules.raw" "modules-$version.qcow2"
